name: graphql_client_annotation
description: Annotations for generating opinionated graphql client class.
version: 0.0.1
repository: https://github.com/iandis/graphql_client_generator

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  graphql: ^5.1.2
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
