name: graphql_client_generator
description: Opinionated graphql client class generator.
version: 0.0.1
repository: https://github.com/iandis/graphql_client_generator

# publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  analyzer: ">=4.6.0 <6.0.0"
  build: ^2.3.1
  graphql: ^5.1.3
  graphql_client_annotation: ^0.0.1
    # path: ../graphql_client_annotation
  source_gen: ^1.2.6

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.16.0
