name: example
description: A starting point for Dart libraries or applications.
version: 1.0.0

publish_to: "none"

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  graphql: ^5.1.3
  graphql_client_annotation:
    path: ../../graphql_client_annotation
  graphql_client_generator:
    path: ../../graphql_client_generator

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.16.0
